src/Entity/File.php
<?php

namespace App\Entity;

use App\File\FileManager;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 */
class File
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mime;

    /**
     * @ORM\Column(type="integer")
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $originalName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMime(): ?string
    {
        return $this->mime;
    }

    public function setMime(string $mime): self
    {
        $this->mime = $mime;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getOriginalName(): ?string
    {
        return $this->originalName;
    }

    public function setOriginalName(string $originalName): self
    {
        $this->originalName = $originalName;

        return $this;
    }

    public function getFilePath(): string
    {
        return FileManager::FILES_DIR . DIRECTORY_SEPARATOR . $this->getName();
    }

    public function fullName()
    {
        return $this->getOriginalName() . '.' . $this->getMime();
    }
}

src/Controller/StaticPagesController.php
<?php

namespace App\Controller;

use App\Annotation\SiteMap;
use App\Entity\Credit;
use App\Entity\Department;
use App\Entity\OnlineApplication\OnlineApplication;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;

class StaticPagesController extends BaseController
{
    /**
     * @var Breadcrumbs
     */
    private $breadcrumbs;
    /**
     * @var TranslatorInterface
     */
    private $translator;

    /**
     * @param Breadcrumbs $breadcrumbs
     * @param TranslatorInterface $translator
     */
    public function __construct(Breadcrumbs $breadcrumbs, TranslatorInterface $translator)
    {
        $this->breadcrumbs = $breadcrumbs;
        $this->translator = $translator;
    }

    /**
     * @Route("", name="static_pages.home_page")
     * @SiteMap()
     * @return Response
     * @throws Exception
     */
    public function homePageAction()
    {
        $credits = $this->manager()->getRepository(Credit::class)->findAll();

        return $this->render(
            'static_pages/home_page.html.twig',
            [
                'credits' => $credits,
                'loyaltyProgramUrl' => $this->generateUrl('loyalty_program.index'),
            ]
        );
    }

    /**
     * @return Response
     * @Route({"en": "/about-us", "ua": "/pro-nas", "ru": "/about-us"}, name="static_pages.about_us")
     * @SiteMap()
     */
    public function aboutUsAction()
    {
        $this->breadcrumbs->addItem($this->translator->trans('public.title.home', [], 'text'), $this->generateUrl('static_pages.home_page'));
        $this->breadcrumbs->addItem($this->translator->trans('static_pages.title.about_us', [], 'text'), null);

        $departments = $this->manager()->getRepository(Department::class)->findVisible();
        $hasDepartments = count($departments) > 0;
        $mainDepartment = array_shift($departments);

        return $this->render(
            'static_pages/about_us.html.twig',
            [
                'mainDepartment' => $mainDepartment,
                'departments' => $departments,
                'hasDepartments' => $hasDepartments,
            ]
        );
    }
}

templates/static_pages/about_us.html.twig
{% extends 'base.html.twig' %}

{% block customSeoTags %}
    <meta name="title" content="【Хто ми】iCredit - iCredit "/>
    <meta name="description" content="Понад 800 співробітників та майже 600 кредитних консультантів ⚫ Понад 300 000 позик 【iCredit】 Дізнайтеся більше на сайті ➤ або за номером ☎0800601810">
    <meta name="keywords" content="місія, цінності, цілі, співробітники, клієнти, комунікація, якість, послуга, партнер, айкредит, iCredit, фінанси, кредит, фінансова послуга">

    <meta property="og:title" content="【Хто ми】iCredit - iCredit "/>
    <meta property="og:description" content="Понад 800 співробітників та майже 600 кредитних консультантів ⚫ Понад 300 000 позик 【iCredit】 Дізнайтеся більше на сайті ➤ або за номером ☎0800601810">
{% endblock %}

{% block title %}
    【Хто ми】iCredit | {{ 'page_title.symfony_starter'|trans({}, 'text') }}
{% endblock %}

{% block headline %}
    {{ 'static_pages.title.about_us'|trans({}, 'text') }}
{% endblock %}

{% block content %}
    {{ render_named_module('Content [About Us: Who are we]') }}

    {{ render_named_module('Content [About Us: Mission and vision]') }}

    {% if hasDepartments %}
        <section class="departments space">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% if mainDepartment|default %}
                            <h2 class="heading text-center">{{ 'static_pages.title.about_us.deparments'|trans({}, 'text') }}</h2>

                            <div class="row justify-content-center">
                                <div class="col-md-6">
                                    <div class="department">
                                        <figure style="min-height: 170px; overflow: hidden; text-align: center;">
                                            <img src="{% if mainDepartment.image %}{{ mainDepartment.image.filePath|imagine_filter('index_thumbnail') }}{% else %}{{ asset('build/images/icredit-default-img.jpg') }}{% endif %}"
                                                 class="img-fluid w-100" alt="{{ mainDepartment.name }}">
                                        </figure>

                                        <div class="content">
                                            <h5 class="title">{{ mainDepartment.name }}</h5>
                                            <p class="desc">{{ mainDepartment.director }}</p>

                                            <a href="#" class="btn btn-danger" data-toggle="modal"
                                               data-target="#department_{{ mainDepartment.id }}">
                                                {{ 'learn_more'|trans({}, 'text') }}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <div class="row">
                            {% for department in departments %}
                                <div class="col-xl-4 col-md-6">
                                    <div class="department">
                                        <figure style="min-height: 170px; overflow: hidden; text-align: center;">
                                            <img class="img-fluid w-100" src="{% if department.image %}{{ department.image.filePath|imagine_filter('index_thumbnail') }}{% else %}{{ asset('build/images/icredit-default-img.jpg') }}{% endif %}" class="img-fluid" alt="{{ department.name }}">
                                        </figure>
                                        <div class="content">
                                            <h5 class="title">{{ department.name }}</h5>
                                            <p class="desc">{{ department.director }}</p>
                                            <a href="#" class="btn btn-danger" data-toggle="modal"
                                               data-target="#department_{{ department.id }}">
                                                {{ 'learn_more'|trans({}, 'text') }}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        {% if mainDepartment|default %}
                            <modal title="{{ mainDepartment.name }}" identifier="department_{{ mainDepartment.id }}" size="lg"
                                   :vertically-centered="true" :has-footer=false>
                                <p class="text-muted">{{ mainDepartment.director }}</p>
                                <p class="ck-content">{{ mainDepartment.description|raw }}</p>
                            </modal>
                        {% endif %}

                        {% for department in departments %}
                            <modal title="{{ department.name }}" identifier="department_{{ department.id }}" size="lg"
                                   :vertically-centered="true" :has-footer=false>
                                <p class="text-muted">{{ department.director }}</p>
                                <p class="ck-content">{{ department.description|raw }}</p>
                            </modal>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}

templates/static_pages/bring_friends.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'public.title.bring_friend'|trans({}, 'text') }} | {{ 'page_title.symfony_starter'|trans({}, 'text') }}{% endblock %}

{% block headline %}
    {{ 'public.headline.bring_friend'|trans({}, 'text') }}
{% endblock %}

{% block content %}
    {{ render_named_module('Content [Bring a friend]') }}
{% endblock %}